Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.provision :shell, 
  path: "islandora.build.sh",
  keep_color: true
  config.vm.synced_folder "..", "/demo_repository_deployments", :mount_options => ["dmode=777","fmode=777"]
  config.vm.network :forwarded_port, host: 9999, guest: 80
  config.vm.network :forwarded_port, host: 8080, guest: 8080
  config.vm.network :forwarded_port, host: 4000, guest: 4000
  config.vbguest.auto_update = false
  config.vm.define 'islandora' do |t|
    config.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 10240]
    end
  end
end
